version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
      continueDeployment: true 
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
