version: 0.2

phases:

  build:
    commands:
      - docker build -t danyalharoon/goapp:latest 

 # post_build:
    
  #  commands:
   #   - docker tag goapp:latest danyalharoon/goapp:latest
    #  - docker push danyalharoon/goapp:latest 

#artifacts:
 # files: myapp
