version: 0.2

phases:

  build:
    commands:
      - docker build -t myapp .

  post_build:
    commands:
      - docker login --username=danyalharoon --email=danyal.haroon@emumba.com
      - docker tag myapp:latest danyalharoon/goapp:latest
      - docker push danyalharoon/goapp

#artifacts:
 # files: myapp
