version: 0.2

phases:

  build:
    commands:
      - docker build -t myapp:latest .

  post_build:
    run-as: root 
    commands:
  
      - docker tag myapp:latest danyalharoon/goapp:latest
      - docker push danyalharoon/goapp

#artifacts:
 # files: myapp
