version: '3.8'

services:
  # Go App Container
  go-app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=mysql_container2
      - DB_USER=root
      - DB_PASS=danyal123
      - DB_PORT=3306
      - DB_DATABASE=gotodo
    depends_on:
      - mysql_container2

  # MySQL Container
  mysql_container2:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=danyal123
      - MYSQL_DATABASE=gotodo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=danyal123
    ports:
      - "3308:3306"



